name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key

    - name: Probar conexión SSH
      env:
        HOST_NAME: ${{ secrets.EC2_HOST }}
        USER_NAME: ${{ secrets.EC2_USER_NAME }}
      run: |
        ssh -vvv -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} 'echo "Conexión exitosa"'
